import { useEffect, useState } from 'react'

type Answers = Record<string, string>
const STORAGE = 'famu-action-research-lite-v1'
const steps = [['Welcome','Begin the simulation'],['Notice','Name what is happening'],['Question','Focus the inquiry'],['Plan','Choose an action'],['Evidence','Select useful evidence'],['Analyze','Read the synthetic data'],['Reflect','Interpret with care'],['Act again','Design cycle two'],['Case report','Show what you learned']]
const prompts = {
  1:{title:'What do you notice?',intro:'Begin with the classroom—not a solution. Separate what you can observe from what you assume.',question:'Which pattern is most important to investigate?',options:['Students complete work but rarely explain their reasoning.','Students need a harder grading policy.','Families are not supporting mathematics at home.'],coach:'Strong noticing stays close to observable evidence. The first option describes a pattern without blaming students or families.'},
  2:{title:'Turn the concern into a question',intro:'An action research question names the learners, the action, and the change you will look for.',question:'Choose the strongest research question.',options:['Why are my students weak in algebra?','How does using error-analysis exit tickets twice weekly affect ninth-grade students’ explanations of algebraic reasoning over four weeks?','Do exit tickets work?'],coach:'The strongest question is specific, measurable, time-bound, and open to more than a yes-or-no answer.'},
  3:{title:'Plan one manageable change',intro:'The teacher changes one part of practice, observes carefully, and learns from the result.',question:'Which action best matches the question?',options:['Use a two-question error-analysis exit ticket every Tuesday and Thursday for four weeks.','Replace the entire algebra curriculum.','Give extra credit to students who write longer answers.'],coach:'A useful action is focused enough to carry out consistently and directly connected to the research question.'},
  4:{title:'Gather more than one view',intro:'Triangulation means looking at the same issue through different evidence sources.',question:'Which evidence set gives the clearest, most balanced view?',options:['Exit-ticket reasoning rubric + weekly student confidence pulse + teacher observation notes','Final exam scores only','Names of students who did not participate'],coach:'The first set combines student work, student perspective, and teacher observation. No real student data is used in this simulation.'}
}
const synthetic=[{week:'Baseline',rubric:1.4},{week:'Week 1',rubric:1.7},{week:'Week 2',rubric:2.1},{week:'Week 3',rubric:2.5},{week:'Week 4',rubric:2.8}]

export default function App(){
  const saved=(()=>{try{return JSON.parse(localStorage.getItem(STORAGE)||'{}')}catch{return {}}})()
  const [step,setStep]=useState<number>(saved.step||0),[answers,setAnswers]=useState<Answers>(saved.answers||{}),[showCoach,setShowCoach]=useState(false)
  useEffect(()=>localStorage.setItem(STORAGE,JSON.stringify({step,answers})),[step,answers])
  const goTo=(next:number)=>{setShowCoach(false);setStep(next);window.scrollTo({top:0,behavior:'smooth'})}
  const progress=Math.round(step/(steps.length-1)*100),choose=(v:string)=>setAnswers(a=>({...a,[`step${step}`]:v})),canContinue=step===0||step>=5||Boolean(answers[`step${step}`])
  const content=(()=>{
    if(step===0)return <Welcome onStart={()=>goTo(1)}/>
    if(step<=4){const p=prompts[step as keyof typeof prompts];return <Decision {...p} selected={answers[`step${step}`]} onChoose={choose} showCoach={showCoach} onCoach={()=>setShowCoach(true)}/>}
    if(step===5)return <Analyze selected={answers.interpretation||''} onChoose={v=>setAnswers(a=>({...a,interpretation:v}))}/>
    if(step===6)return <Writing title="What can—and can’t—you conclude?" eyebrow="Reflect" prompt="Write 2–4 sentences. What changed, what remains uncertain, and what is one plausible alternative explanation?" value={answers.reflection||''} onChange={(v:string)=>setAnswers(a=>({...a,reflection:v}))} tip="Avoid saying the action ‘proved’ a cause. Four weeks of synthetic classroom data can suggest a useful pattern, not establish certainty."/>
    if(step===7)return <Writing title="Plan the next spiral" eyebrow="Act again" prompt="What would you keep, adjust, and examine during a second cycle?" value={answers.cycleTwo||''} onChange={(v:string)=>setAnswers(a=>({...a,cycleTwo:v}))} tip="Action research is a spiral: plan → act → observe → reflect → plan again."/>
    return <Report answers={answers} ready={Boolean(answers.reflection&&answers.cycleTwo)}/>
  })()
  return <div className="shell"><header className="topbar"><a className="brand" href="#" onClick={e=>{e.preventDefault();setStep(0)}}><span className="mark">AR</span><span>FAMU COE <b>Action Research Lite</b></span></a><div className="simulation">Undergraduate learning simulation</div><button className="text-button" onClick={()=>{if(confirm('Clear this simulation and start again?')){localStorage.removeItem(STORAGE);setAnswers({});setStep(0)}}}>Start over</button></header><div className="layout"><aside className="sidebar" aria-label="Learning cycle"><div className="progress-label"><span>YOUR PROGRESS</span><b>{progress}%</b></div><div className="progress-track"><i style={{width:`${progress}%`}}/></div><nav>{steps.map((s,i)=><button key={s[0]} className={i===step?'active':i<step?'done':''} onClick={()=>i<=step&&setStep(i)} disabled={i>step}><span>{i<step?'✓':i+1}</span><em>{s[0]}<small>{s[1]}</small></em></button>)}</nav><div className="guardrail"><b>Practice space</b><p>Fictional case. Synthetic data. No real student information.</p></div></aside><main className="main"><div className="content">{content}</div>{step>0&&step<8&&<footer className="controls"><button className="back" onClick={()=>setStep(s=>s-1)}>← Back</button><button className="next" disabled={!canContinue} onClick={()=>setStep(s=>s+1)}>Continue <span>→</span></button></footer>}</main></div></div>
}

function Welcome({onStart}:{onStart:()=>void}){return <section className="welcome"><p className="eyebrow">LEARN BY DOING</p><h1>Experience one complete<br/><i>action research cycle.</i></h1><p className="lede">You are the teacher-researcher in a fictional ninth-grade algebra classroom. Make decisions, examine synthetic evidence, and see how reflection leads to a better next action.</p><div className="case-card"><div><span>YOUR FICTIONAL CASE</span><h2>When answers are right—but reasoning is missing</h2><p>Many students in Ms. Reed’s Algebra I class can select a correct answer, but struggle to explain why a solution works or identify where an error occurred.</p></div><div className="case-facts"><p><b>24</b> fictional students</p><p><b>4</b> week cycle</p><p><b>3</b> evidence sources</p></div></div><div className="promise"><div><b>1</b><span>Make a choice</span></div><div><b>2</b><span>Explain your thinking</span></div><div><b>3</b><span>Compare with a coach</span></div><div><b>4</b><span>Build a case report</span></div></div><button className="start" onClick={onStart}>Begin the learning cycle <span>→</span></button><p className="fineprint">About 20 minutes · Progress stays on this device</p></section>}

function Decision({title,intro,question,options,coach,selected,onChoose,showCoach,onCoach}:any){return <section><p className="eyebrow">MAKE A RESEARCH DECISION</p><h1>{title}</h1><p className="lede narrow">{intro}</p><div className="question-card"><h2>{question}</h2><div className="options">{options.map((o:string,i:number)=><button key={o} className={selected===o?'selected':''} onClick={()=>onChoose(o)}><span>{String.fromCharCode(65+i)}</span><p>{o}</p><i>{selected===o?'✓':''}</i></button>)}</div></div>{selected&&<div className="coach"><div className="coach-head"><span>COACH’S LENS</span>{!showCoach&&<button onClick={onCoach}>Compare your thinking</button>}</div>{showCoach&&<p>{coach}</p>}</div>}</section>}

function Analyze({selected,onChoose}:{selected:string,onChoose:(v:string)=>void}){const opts=['The intervention definitively caused every student to improve.','Reasoning scores and confidence rose together, suggesting a promising pattern worth examining in another cycle.','The class improved, so no further inquiry is needed.'];return <section><p className="eyebrow">ANALYZE SYNTHETIC EVIDENCE</p><h1>What story does the data tell?</h1><p className="lede narrow">Look for patterns across sources. Choose the interpretation supported without claiming more than the evidence can show.</p><div className="dashboard"><div className="chart"><div className="chart-title"><span>Reasoning rubric average</span><b>Scale: 0–4</b></div><div className="bars">{synthetic.map(d=><div key={d.week}><span>{d.rubric}</span><i style={{height:`${d.rubric/4*100}%`}}/><small>{d.week}</small></div>)}</div></div><div className="signals"><span>STUDENT CONFIDENCE</span><b>42% <i>→</i> 68%</b><p>“I check where the reasoning changed, not just whether I got it wrong.”</p><small>— Synthetic student pulse, Week 4</small></div></div><div className="question-card compact"><h2>Which interpretation is most responsible?</h2><div className="options">{opts.map((o,i)=><button key={o} className={selected===o?'selected':''} onClick={()=>onChoose(o)}><span>{String.fromCharCode(65+i)}</span><p>{o}</p><i>{selected===o?'✓':''}</i></button>)}</div></div></section>}

function Writing({title,eyebrow,prompt,value,onChange,tip}:any){return <section><p className="eyebrow">{eyebrow}</p><h1>{title}</h1><p className="lede narrow">{prompt}</p><div className="writing"><label>Your thinking</label><textarea value={value} onChange={e=>onChange(e.target.value)} placeholder="Write in your own words…" rows={8}/><div className="wordline"><span>{value.trim()?value.trim().split(/\s+/).length:0} words</span><span>Your response becomes part of the case report.</span></div></div><div className="tip"><b>Research habit</b><p>{tip}</p></div></section>}

function Report({answers,ready}:{answers:Answers,ready:boolean}){return <section><p className="eyebrow">YOUR LEARNING PRODUCT</p><h1>Action Research Case Report</h1><p className="lede narrow">This report documents how you reasoned through a simulated cycle. It is an instructional artifact—not original research.</p>{!ready?<div className="empty"><h2>Your reflection is not finished yet.</h2><p>Complete the reflection and second-cycle plan to assemble your report.</p></div>:<article className="report"><div className="watermark">INSTRUCTIONAL SIMULATION · NOT ORIGINAL RESEARCH</div><header><p>FAMU COLLEGE OF EDUCATION</p><h2>Improving Algebraic Reasoning Through Error-Analysis Exit Tickets</h2><span>Undergraduate Action Research Learning Lab · Fictional case · Synthetic data</span></header><ReportSection n="01" title="Problem of practice" text="Ninth-grade Algebra I students often select correct answers but do not explain why a solution works or identify errors in reasoning."/><ReportSection n="02" title="Inquiry question" text={answers.step2}/><ReportSection n="03" title="Action and evidence" text={`${answers.step3} Evidence: ${answers.step4}`}/><div className="report-data"><b>Observed synthetic pattern</b><span><strong>1.4 → 2.8</strong> reasoning rubric average</span><span><strong>42% → 68%</strong> student confidence</span></div><ReportSection n="04" title="Responsible interpretation" text={answers.interpretation}/><ReportSection n="05" title="Reflection and limitations" text={answers.reflection}/><ReportSection n="06" title="Cycle two" text={answers.cycleTwo}/><footer>Generated by Action Research Lite · Learning demonstration only</footer></article>}<div className="report-actions"><button onClick={()=>window.print()} disabled={!ready}>Print / Save as PDF</button><button className="back" onClick={()=>{localStorage.removeItem(STORAGE);location.reload()}}>Try another cycle</button></div></section>}
function ReportSection({n,title,text}:{n:string,title:string,text?:string}){return <section className="report-section"><span>{n}</span><div><h3>{title}</h3><p>{text||'Not completed'}</p></div></section>}
