import { useEffect, useMemo, useState } from 'react'

type Answers = Record<string, string>
type CaseStudy = { id:string; subject:string; title:string; summary:string; learners:string; duration:string; problem:string; question:string; action:string; evidence:string; baseline:number; weekly:number[]; confidence:[number,number]; quote:string }
const STORAGE='famu-action-research-learning-lab-v2'
const stages=[['Welcome','Understand the practice space'],['Boundaries','Confirm this is a simulation'],['Case','Choose a fictional classroom'],['Notice','Name what is happening'],['Question','Focus the inquiry'],['Plan','Choose one action'],['Evidence','Gather more than one view'],['Analyze','Read synthetic data'],['Reflect','Interpret with care'],['Act again','Design cycle two'],['Case report','Show what you learned']]
const cases:CaseStudy[]=[
  {id:'algebra',subject:'Mathematics',title:'Right answers, missing reasoning',learners:'24 fictional ninth-grade students',duration:'4 weeks',summary:'Students often select a correct algebra answer but struggle to explain why a solution works or locate an error.',problem:'Students complete algebra problems but rarely explain their reasoning or identify where an error occurred.',question:'How does using error-analysis exit tickets twice weekly affect ninth-grade students’ explanations of algebraic reasoning over four weeks?',action:'Use a two-question error-analysis exit ticket every Tuesday and Thursday for four weeks.',evidence:'Reasoning rubric + weekly confidence pulse + teacher observation notes',baseline:1.4,weekly:[1.7,2.1,2.5,2.8],confidence:[42,68],quote:'I check where the reasoning changed, not just whether I got it wrong.'},
  {id:'reading',subject:'Elementary literacy',title:'Reading fluency without expression',learners:'18 fictional third-grade students',duration:'5 weeks',summary:'Students read grade-level passages accurately, yet their phrasing and expression make comprehension harder to hear.',problem:'Students read most words accurately but use limited phrasing and expression during oral reading.',question:'How does repeated partner reading with modeled phrasing affect third-grade students’ oral-reading expression over five weeks?',action:'Use a ten-minute modeled partner-reading routine three times each week for five weeks.',evidence:'Fluency rubric + student audio self-rating + teacher conference notes',baseline:1.6,weekly:[1.8,2.0,2.3,2.6],confidence:[47,73],quote:'Listening back helped me hear where my voice sounded flat.'},
  {id:'science',subject:'Middle grades science',title:'Ideas stay silent in group work',learners:'27 fictional seventh-grade students',duration:'4 weeks',summary:'A few voices dominate laboratory discussions even when other students record useful observations.',problem:'Laboratory groups record useful observations, but discussion participation is uneven and many ideas remain unspoken.',question:'How do rotating discussion roles affect equitable participation in seventh-grade laboratory sensemaking over four weeks?',action:'Assign and rotate facilitator, evidence-checker, connector, and reporter roles during two labs each week.',evidence:'Participation tally + group reflection slip + teacher field notes',baseline:1.3,weekly:[1.5,1.9,2.2,2.6],confidence:[38,64],quote:'My role gave me a reason to say what I noticed instead of waiting.'}
]
const getCase=(id?:string)=>cases.find(item=>item.id===id)??cases[0]

export default function LearningLab(){
  const saved=useMemo(()=>{try{return JSON.parse(localStorage.getItem(STORAGE)||'{}')}catch{return {}}},[])
  const [step,setStep]=useState<number>(saved.step||0),[answers,setAnswers]=useState<Answers>(saved.answers||{}),[showCoach,setShowCoach]=useState(false),[showTutorial,setShowTutorial]=useState(false)
  const study=getCase(answers.caseId)
  useEffect(()=>localStorage.setItem(STORAGE,JSON.stringify({step,answers})),[step,answers])
  useEffect(()=>{if(!showTutorial)return;const close=(event:KeyboardEvent)=>event.key==='Escape'&&setShowTutorial(false);document.addEventListener('keydown',close);return()=>document.removeEventListener('keydown',close)},[showTutorial])
  const goTo=(next:number)=>{setShowCoach(false);setStep(next);window.scrollTo({top:0,behavior:'smooth'})}
  const setAnswer=(key:string,value:string)=>setAnswers(current=>({...current,[key]:value}))
  const reset=()=>{if(confirm('Clear this learning simulation and start again?')){localStorage.removeItem(STORAGE);setAnswers({});setStep(0)}}
  const progress=Math.round(step/(stages.length-1)*100)
  const canContinue=step===0||(step===1&&answers.useIntent==='simulation')||(step===2&&Boolean(answers.caseId))||(step>=3&&step<=7&&Boolean(answers[`step${step}`]))||(step===8&&Boolean(answers.reflection?.trim()))||(step===9&&Boolean(answers.cycleTwo?.trim()))
  let content
  if(step===0)content=<Welcome onStart={()=>goTo(1)} onWatchTutorial={()=>setShowTutorial(true)}/>
  else if(step===1)content=<Boundary selected={answers.useIntent} onChoose={value=>setAnswer('useIntent',value)}/>
  else if(step===2)content=<CaseLibrary selected={answers.caseId} onChoose={value=>setAnswer('caseId',value)}/>
  else if(step===3)content=<Decision title="What do you notice?" intro="Begin with the classroom—not a solution. Separate what can be observed from what is assumed." question="Which statement is the strongest problem of practice?" options={[study.problem,'The students are unmotivated and their families need to do more.','The school should replace its entire curriculum.']} coach="Strong noticing stays close to observable evidence. It describes a pattern without blaming learners or claiming a cause too soon." selected={answers.step3} onChoose={(value:string)=>setAnswer('step3',value)} showCoach={showCoach} onCoach={()=>setShowCoach(true)}/>
  else if(step===4)content=<Decision title="Turn the concern into a question" intro="A useful action research question names the learners, the action, the evidence, and a manageable time frame." question="Choose the question that can guide one inquiry cycle." options={[`Why are these ${study.subject.toLowerCase()} students struggling?`,study.question,'Does the strategy work?']} coach="The strongest question is focused, answerable with classroom evidence, time-bound, and open to more than a yes-or-no answer." selected={answers.step4} onChoose={(value:string)=>setAnswer('step4',value)} showCoach={showCoach} onCoach={()=>setShowCoach(true)}/>
  else if(step===5)content=<Decision title="Plan one manageable change" intro="The teacher changes one part of practice, observes carefully, and learns from the result." question="Which action aligns best with the inquiry question?" options={[study.action,'Replace the entire course curriculum immediately.','Give extra credit only to students whose scores improve.']} coach="A useful action is feasible, repeatable, and directly connected to the question. It should be small enough to revise after one cycle." selected={answers.step5} onChoose={(value:string)=>setAnswer('step5',value)} showCoach={showCoach} onCoach={()=>setShowCoach(true)}/>
  else if(step===6)content=<Decision title="Gather more than one view" intro="Triangulation means examining the same issue through different kinds of evidence." question="Which evidence set gives the clearest, most balanced view?" options={[study.evidence,'One final score only','A public list naming students who did not participate']} coach="A balanced plan combines performance evidence, learner perspective, and teacher observation. In this Learning Lab, every record is fictional and synthetic." selected={answers.step6} onChoose={(value:string)=>setAnswer('step6',value)} showCoach={showCoach} onCoach={()=>setShowCoach(true)}/>
  else if(step===7)content=<Analyze study={study} selected={answers.step7||''} onChoose={value=>setAnswer('step7',value)}/>
  else if(step===8)content=<Writing title="What can—and can’t—you conclude?" eyebrow="REFLECT" prompt="Write 2–4 sentences. What changed, what remains uncertain, and what is one plausible alternative explanation?" value={answers.reflection||''} onChange={(value:string)=>setAnswer('reflection',value)} tip="Do not say the action proved a cause. A short cycle can reveal a promising pattern, not establish certainty."/>
  else if(step===9)content=<Writing title="Plan the next spiral" eyebrow="ACT AGAIN" prompt="What would you keep, adjust, and examine during a second cycle?" value={answers.cycleTwo||''} onChange={(value:string)=>setAnswer('cycleTwo',value)} tip="Action research is iterative: plan → act → observe → reflect → plan again."/>
  else content=<Report answers={answers} study={study} ready={Boolean(answers.reflection&&answers.cycleTwo)} onRestart={reset}/>
  return <div className="shell"><header className="topbar"><a className="brand" href="#" onClick={event=>{event.preventDefault();goTo(0)}}><span className="mark">AR</span><span>FAMU COE <b>Action Research Learning Lab</b></span></a><div className="simulation">Undergraduate instructional simulation</div><button className="text-button" onClick={reset}>Start over</button></header><div className="layout"><aside className="sidebar" aria-label="Learning cycle"><div className="progress-label"><span>YOUR PROGRESS</span><b>{progress}%</b></div><div className="progress-track"><i style={{width:`${progress}%`}}/></div><nav>{stages.map((stage,index)=><button key={stage[0]} className={index===step?'active':index<step?'done':''} onClick={()=>index<=step&&goTo(index)} disabled={index>step}><span>{index<step?'✓':index+1}</span><em>{stage[0]}<small>{stage[1]}</small></em></button>)}</nav><div className="guardrail"><b>Practice space</b><p>Fictional cases. Synthetic data. No real participant information.</p></div></aside><main className="main"><div className="content">{content}</div>{step>0&&step<10&&<footer className="controls"><button className="back" onClick={()=>goTo(step-1)}>← Back</button><button className="next" disabled={!canContinue} onClick={()=>goTo(step+1)}>Continue <span>→</span></button></footer>}</main></div>{showTutorial&&<TutorialModal onClose={()=>setShowTutorial(false)}/>}</div>
}

function Welcome({onStart,onWatchTutorial}:{onStart:()=>void,onWatchTutorial:()=>void}){return <section className="welcome"><p className="eyebrow">LEARN BY DOING</p><h1>Practice the thinking behind<br/><i>action research.</i></h1><p className="lede">Step into a fictional classroom, make the decisions a teacher-researcher makes, examine synthetic evidence, and revise the next cycle. The Lab teaches the process; it does not conduct real research for you.</p><button className="tutorial-card" onClick={onWatchTutorial}><span className="tutorial-poster"><img src="/tutorial/action-research-learning-lab-tutorial-poster.jpg" alt="Preview of the Action Research Learning Lab tutorial"/><i aria-hidden="true">▶</i></span><span className="tutorial-copy"><small>START HERE · 3 MINUTES</small><strong>Watch the Learning Lab tutorial</strong><em>Dr. White walks through the complete simulation, its safeguards, and the learning report.</em><b>Watch tutorial →</b></span></button><div className="case-card welcome-card"><div><span>THE LEARNING EXPERIENCE</span><h2>A flight simulator for practitioner inquiry</h2><p>Make a choice first. Then compare your reasoning with a coach’s lens. Finish with a watermarked report that shows what you learned.</p></div><div className="case-facts"><p><b>3</b> fictional cases</p><p><b>1</b> complete cycle</p><p><b>0</b> real participants</p></div></div><div className="promise"><div><b>1</b><span>Choose a case</span></div><div><b>2</b><span>Make decisions</span></div><div><b>3</b><span>Read evidence</span></div><div><b>4</b><span>Revise the cycle</span></div></div><button className="start" onClick={onStart}>Enter the Learning Lab <span>→</span></button><p className="fineprint">About 20–25 minutes · Progress stays on this device</p></section>}
function TutorialModal({onClose}:{onClose:()=>void}){return <div className="tutorial-backdrop" role="presentation" onMouseDown={event=>event.target===event.currentTarget&&onClose()}><section className="tutorial-modal" role="dialog" aria-modal="true" aria-labelledby="tutorial-title"><header><div><span>FAMU COE LEARNING LAB</span><h2 id="tutorial-title">How the Action Research Learning Lab works</h2></div><button onClick={onClose} aria-label="Close tutorial">×</button></header><div className="video-frame"><video controls autoPlay playsInline preload="metadata" poster="/tutorial/action-research-learning-lab-tutorial-poster.jpg"><source src="/tutorial/action-research-learning-lab-tutorial.mp4" type="video/mp4"/><track kind="captions" src="/tutorial/action-research-learning-lab-tutorial.vtt" srcLang="en" label="English"/>Your browser does not support embedded video.</video></div><footer><span>3:17 · Narrated by Dr. White · Captions included</span><button onClick={onClose}>Close and continue</button></footer></section></div>}
function Boundary({selected,onChoose}:{selected?:string,onChoose:(value:string)=>void}){const blocked=selected&&selected!=='simulation';return <section><p className="eyebrow">BEFORE YOU BEGIN</p><h1>Choose the right research space.</h1><p className="lede narrow">The Learning Lab is intentionally limited to undergraduate practice with fictional cases and synthetic data.</p><div className="intent-grid"><button className={selected==='simulation'?'intent-card selected':'intent-card'} onClick={()=>onChoose('simulation')}><span>01</span><h2>I want to practice</h2><p>Learn the action research cycle using a fictional classroom case.</p><b>Use the Learning Lab →</b></button><button className={selected==='real'?'intent-card selected blocked':'intent-card'} onClick={()=>onChoose('real')}><span>02</span><h2>I have real participants or data</h2><p>Plan an authentic classroom, school, or community inquiry.</p><b>Use the full Navigator instead</b></button><button className={selected==='graduate'?'intent-card selected blocked':'intent-card'} onClick={()=>onChoose('graduate')}><span>03</span><h2>This is graduate or published work</h2><p>Prepare a thesis, dissertation, IRB study, or publication.</p><b>Use faculty-approved research support</b></button></div>{blocked&&<div className="stop-notice"><strong>This Learning Lab stops here.</strong><p>It cannot accept real participant information or create graduate-level research. Return to the original Action Research Navigator and follow your institution’s faculty and ethics requirements.</p></div>}</section>}
function CaseLibrary({selected,onChoose}:{selected?:string,onChoose:(value:string)=>void}){return <section><p className="eyebrow">CHOOSE A FICTIONAL CASE</p><h1>Which classroom will you enter?</h1><p className="lede narrow">Each case follows the same inquiry cycle with different learners, evidence, and instructional choices.</p><div className="case-library">{cases.map((item,index)=><button key={item.id} className={selected===item.id?'library-card selected':'library-card'} onClick={()=>onChoose(item.id)}><div><span>CASE {String(index+1).padStart(2,'0')} · {item.subject}</span><i>{selected===item.id?'✓':'→'}</i></div><h2>{item.title}</h2><p>{item.summary}</p><small>{item.learners} · {item.duration}</small></button>)}</div><div className="privacy-strip"><b>Safe by design</b><span>No uploads</span><span>No names</span><span>No real student records</span><span>No IRB documents</span></div></section>}
function Decision({title,intro,question,options,coach,selected,onChoose,showCoach,onCoach}:any){return <section><p className="eyebrow">MAKE A RESEARCH DECISION</p><h1>{title}</h1><p className="lede narrow">{intro}</p><div className="question-card"><h2>{question}</h2><div className="options">{options.map((option:string,index:number)=><button key={option} className={selected===option?'selected':''} onClick={()=>onChoose(option)}><span>{String.fromCharCode(65+index)}</span><p>{option}</p><i>{selected===option?'✓':''}</i></button>)}</div></div>{selected&&<div className="coach"><div className="coach-head"><span>COACH’S LENS</span>{!showCoach&&<button onClick={onCoach}>Compare your thinking</button>}</div>{showCoach&&<p>{coach}</p>}</div>}</section>}
function Analyze({study,selected,onChoose}:{study:CaseStudy,selected:string,onChoose:(value:string)=>void}){const points=[{week:'Baseline',value:study.baseline},...study.weekly.map((value,index)=>({week:`Week ${index+1}`,value}))];const options=['The intervention definitively caused every learner to improve.','The evidence sources moved in a promising direction, suggesting a pattern worth examining in another cycle.','The group improved, so no further inquiry is needed.'];return <section><p className="eyebrow">ANALYZE SYNTHETIC EVIDENCE</p><h1>What story does the evidence tell?</h1><p className="lede narrow">Look for convergence and tension across sources. Choose an interpretation that is useful without claiming more than the evidence can show.</p><div className="dashboard"><div className="chart"><div className="chart-title"><span>Target rubric average</span><b>Scale: 0–4</b></div><div className="bars">{points.map(point=><div key={point.week}><span>{point.value}</span><i style={{height:`${point.value/4*100}%`}}/><small>{point.week}</small></div>)}</div></div><div className="signals"><span>LEARNER CONFIDENCE</span><b>{study.confidence[0]}% <i>→</i> {study.confidence[1]}%</b><p>“{study.quote}”</p><small>— Synthetic learner pulse, final week</small></div></div><div className="question-card compact"><h2>Which interpretation is most responsible?</h2><div className="options">{options.map((option,index)=><button key={option} className={selected===option?'selected':''} onClick={()=>onChoose(option)}><span>{String.fromCharCode(65+index)}</span><p>{option}</p><i>{selected===option?'✓':''}</i></button>)}</div></div></section>}
function Writing({title,eyebrow,prompt,value,onChange,tip}:any){const words=value.trim()?value.trim().split(/\s+/).length:0;return <section><p className="eyebrow">{eyebrow}</p><h1>{title}</h1><p className="lede narrow">{prompt}</p><div className="writing"><label>Your thinking</label><textarea value={value} onChange={event=>onChange(event.target.value)} placeholder="Write in your own words…" rows={8}/><div className="wordline"><span>{words} words</span><span>Your response becomes part of the learning report.</span></div></div><div className="tip"><b>Research habit</b><p>{tip}</p></div></section>}
function Report({answers,study,ready,onRestart}:{answers:Answers,study:CaseStudy,ready:boolean,onRestart:()=>void}){return <section><p className="eyebrow">YOUR LEARNING PRODUCT</p><h1>Action Research Learning Report</h1><p className="lede narrow">This report documents how you reasoned through a simulated cycle. It is an instructional artifact—not original research and not a submission-ready research paper.</p>{!ready?<div className="empty"><h2>Your reflection is not finished yet.</h2><p>Complete the reflection and second-cycle plan to assemble your report.</p></div>:<article className="report"><div className="watermark">INSTRUCTIONAL SIMULATION · NOT ORIGINAL RESEARCH</div><header><p>FAMU COLLEGE OF EDUCATION</p><h2>{study.title}</h2><span>Undergraduate Action Research Learning Lab · Fictional case · Synthetic data</span></header><ReportSection n="01" title="Problem of practice" text={answers.step3}/><ReportSection n="02" title="Inquiry question" text={answers.step4}/><ReportSection n="03" title="Action and evidence" text={`${answers.step5} Evidence: ${answers.step6}`}/><div className="report-data"><b>Observed synthetic pattern</b><span><strong>{study.baseline} → {study.weekly.at(-1)}</strong> target rubric average</span><span><strong>{study.confidence[0]}% → {study.confidence[1]}%</strong> learner confidence</span></div><ReportSection n="04" title="Responsible interpretation" text={answers.step7}/><ReportSection n="05" title="Reflection and limitations" text={answers.reflection}/><ReportSection n="06" title="Cycle two" text={answers.cycleTwo}/><div className="transfer"><h3>TRANSFER QUESTION</h3><p>What would you need to learn, ask, and protect before applying this process in a real setting?</p></div><footer>Generated by the Action Research Learning Lab · Learning demonstration only</footer></article>}<div className="report-actions"><button onClick={()=>window.print()} disabled={!ready}>Print instructional report</button><button className="back" onClick={onRestart}>Practice another case</button></div></section>}
function ReportSection({n,title,text}:{n:string,title:string,text?:string}){return <section className="report-section"><span>{n}</span><div><h3>{title}</h3><p>{text||'Not completed'}</p></div></section>}
